function out = cpp_start(goals)
out = "";
header = [...
    "#include <Simbody.h>"...
    "#include <OpenSim/OpenSim.h>"...
    "#include <OpenSim/Moco/osimMoco.h>"...
    "#include <OpenSim/Common/TimeSeriesTable.h>"...
    "#include ""mexplus.h"""...
    "#include <vector>"...
    "#include <string>"...
    ];
for line = header
    out = out + line + newline;
end
for goal = goals
    line = "#include """+goal+".h""";
    out = out + line + newline;
end
%% CLASS DEF START
class_def_start = [...
    "using namespace std;",...
    "using namespace mexplus;",...
    "using namespace OpenSim;",...
    "using namespace SimTK;",...
    "",...
    "",...
    "class extendProblem",...
    "{",...
    "public:",...
    "    extendProblem(const __int64 p){",...
    "        m_p = (OpenSim::MocoProblem *) p;",...
    "        mexPrintf(""hello MocoProblem!\n"");",...
    "    }",...
    "    ~extendProblem(){",...
    "        mexPrintf(""goodbye MocoProblem!\n"");",...
    "    }",...
    ];
for line = class_def_start
    out = out + line + newline;
end
end