function out = cpp_end()
out = "";
%% CLASS DEF END
    class_def_end = [...
        "private:",...
        "    OpenSim::MocoProblem *m_p = NULL;",...
        "};",...
        ];
    for line = class_def_end
        out = out + line + newline;
    end
end