function out = mex_start()
out = "";
mex_def_start = [...
    "",...
    "",...
    "",...
    "template class mexplus::Session<extendProblem>;",...
    "",...
    "namespace",...
    "{",...
    "    MEX_DEFINE(new) (int nlhs, mxArray* plhs[], int nrhs, const mxArray* prhs[])",...
    "    {",...
    "        InputArguments input(nrhs, prhs, 1);",...
    "        OutputArguments output(nlhs, plhs, 1);",...
    "        output.set(0, Session<extendProblem>::create(new extendProblem(input.get<__int64>(0))));",...
    "    }",...
    "    MEX_DEFINE(delete) (int nlhs, mxArray* plhs[], int nrhs, const mxArray* prhs[])",...
    "    {",...
    "        InputArguments input(nrhs, prhs, 1);",...
    "        OutputArguments output(nlhs, plhs, 0);",...
    "        Session<extendProblem>::destroy(input.get(0));",...
    "    }",...
    ];
for line = mex_def_start
    out = out + line + newline;
end
end